#!/bin/bash
_MSG=`date "+%y%m%d-%H%M"`
_HOST=`hostname -s`
_CMSG=$@
echo "Comment Message is : $_CMSG"

git add . && git commit -m "$_HOST:$_MSG:$_CMSG"
git push git@gitjoe:joelee-kr/jvPalm.git
#
#git push       git@gitjoe:joelee-kr/jvPalm.git main
#git push -u -f git@gitjoe:joelee-kr/jvPalm.git main
# JOELEE JOELEE
