{
 "title": "Snowflake-2nd",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "snowflake-2nd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Fetched",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- Grafana DB Connection Base is +00:00\n-- therefore, to Presented a HOUR, use +offset \nSELECT date_format(  adddate(START_TIME, interval 9 hour), \"%H:%i:%s\") as T\nFROM palmdb.sf_query_history\nORDER BY START_TIME DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT date_format(START_TIME, \"%m-%d\") AS D\nFROM palmdb.sf_query_history\nORDER BY START_TIME DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Query / 10min State",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "palmdb",
     "rawSql": "SELECT count(*) as \"+10min\"\nfrom palmdb.sf_query_history\nWHERE start_time >= adddate( timestamp( now() ), interval -10 minute )"
    },
    {
     "rawSql": "SELECT count(*) as \"+20min\"\nfrom palmdb.sf_query_history\nWHERE start_time >= adddate( timestamp( now() ), interval -20 minute )"
    },
    {
     "rawSql": "SELECT count(*) as \"+30min\"\nfrom palmdb.sf_query_history\nWHERE start_time >= adddate( timestamp( now() ), interval -30 minute )"
    },
    {
     "rawSql": "SELECT count(*) as \"+40min\"\nfrom palmdb.sf_query_history\nWHERE start_time >= adddate( timestamp( now() ), interval -14 minute )"
    }
   ]
  },
  {
   "title": "Clusters by Warehouse",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n  START_TIME,\n  -- sum(CREDITS_USED_CLOUD_SERVICES),\n  CLUSTER_NUMBER as WH_PRD_LOAD_XS,\n  WAREHOUSE_NAME \nFROM palmdb.sf_query_history\nWHERE WAREHOUSE_NAME='WH_PRD_LOAD_XS'"
    },
    {
     "rawSql": "SELECT \n  START_TIME,\n  -- sum(CREDITS_USED_CLOUD_SERVICES),\n  CLUSTER_NUMBER as WH_DEV_DQM_TEST,\n  WAREHOUSE_NAME \nFROM palmdb.sf_query_history\nWHERE WAREHOUSE_NAME='WH_DEV_DQM_TEST'"
    },
    {
     "rawSql": "SELECT \n  START_TIME,\n  -- sum(CREDITS_USED_CLOUD_SERVICES),\n  CLUSTER_NUMBER as WH_DEV_XS,\n  WAREHOUSE_NAME \nFROM palmdb.sf_query_history\nWHERE WAREHOUSE_NAME='WH_DEV_XS'"
    },
    {
     "rawSql": "SELECT \n  START_TIME,\n  -- sum(CREDITS_USED_CLOUD_SERVICES),\n  CLUSTER_NUMBER AS WH_PRD_XS,\n  WAREHOUSE_NAME \nFROM palmdb.sf_query_history\nWHERE WAREHOUSE_NAME='WH_PRD_XS'"
    }
   ]
  },
  {
   "title": "X-Elapsed TIme (sec)",
   "type": "xychart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dataset": "palmdb",
     "rawSql": "SELECT \n  STARTTIME AS \"DateTime\",\n  TOTAL_ELAPSED_TIME /1000  AS \"SEC\"\nFROM palmdb.sf_query_history \n-- GROUP BY STARTTIME "
    }
   ]
  },
  {
   "title": "Queries Count / min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n  STARTTIME,\n  count(STARTTIME) as WH_PRD_LOAD_XS\n  -- count(CREDITS_USED_CLOUD_SERVICES)\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_PRD_LOAD_XS'\ngroup by STARTTIME\n"
    },
    {
     "rawSql": "SELECT \n  STARTTIME,\n  count(STARTTIME) as WH_DEV_DQM_TEST\n  -- count(CREDITS_USED_CLOUD_SERVICES)\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_DEV_DQM_TEST'\ngroup by STARTTIME"
    },
    {
     "dataset": "palmdb",
     "rawSql": "SELECT \n  STARTTIME,\n  count(STARTTIME) as WH_DEV_XS\n  -- count(CREDITS_USED_CLOUD_SERVICES)\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_DEV_XS'\ngroup by STARTTIME"
    },
    {
     "rawSql": "SELECT \n  STARTTIME,\n  count(STARTTIME) as WH_PRD_XS\n  -- count(CREDITS_USED_CLOUD_SERVICES)\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_PRD_XS'\ngroup by STARTTIME\n"
    }
   ]
  },
  {
   "title": "snowflake-query-history-ALL",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "palmdb",
     "rawSql": "SELECT * \nFROM palmdb.sf_query_history"
    }
   ]
  },
  {
   "title": "Sum Elapsed Times / min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT \n  STARTTIME,\n  sum(TOTAL_ELAPSED_TIME) /1000 as WH_PRD_LOAD_XS\n  -- count(CREDITS_USED_CLOUD_SERVICES)\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_PRD_LOAD_XS'\ngroup by STARTTIME\n"
    },
    {
     "rawSql": "SELECT \n  STARTTIME,\n  sum(TOTAL_ELAPSED_TIME) /1000 as WH_DEV_DQM_TEST\n  -- count(CREDITS_USED_CLOUD_SERVICES)\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_DEV_DQM_TEST'\ngroup by STARTTIME"
    },
    {
     "dataset": "palmdb",
     "rawSql": "SELECT \n  STARTTIME,\n  sum(TOTAL_ELAPSED_TIME)/1000 as WH_DEV_XS\n  -- count(CREDITS_USED_CLOUD_SERVICES)\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_DEV_XS'\ngroup by STARTTIME"
    },
    {
     "rawSql": "SELECT \n  STARTTIME,\n  sum(TOTAL_ELAPSED_TIME) /1000 as WH_PRD_XS\n  -- count(CREDITS_USED_CLOUD_SERVICES)\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_PRD_XS'\ngroup by STARTTIME\n"
    }
   ]
  },
  {
   "title": "Sum Credits / min (APPROXIMATELY)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \n  STARTTIME,\n  sum(CREDITS_USED_CLOUD_SERVICES) *45 as WH_PRD_LOAD_XS\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_PRD_LOAD_XS'\ngroup by STARTTIME"
    },
    {
     "dataset": "palmdb",
     "rawSql": "SELECT \n  STARTTIME,\n  sum(CREDITS_USED_CLOUD_SERVICES)*45 as WH_DEV_DQM_TEST\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_DEV_DQM_TEST'\ngroup by STARTTIME"
    },
    {
     "rawSql": "SELECT \n  STARTTIME,\n  sum(CREDITS_USED_CLOUD_SERVICES)*45 as WH_DEV_XS\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_DEV_XS'\ngroup by STARTTIME"
    },
    {
     "rawSql": "SELECT \n  STARTTIME,\n  sum(CREDITS_USED_CLOUD_SERVICES)*45 as WH_PRD_XS\nFROM palmdb.sf_query_history \nWHERE WAREHOUSE_NAME='WH_PRD_XS'\ngroup by STARTTIME"
    }
   ]
  }
 ]
}